<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orchid.DataAccess\Orchid.DataAccess.csproj" />
    <ProjectReference Include="..\Orchid.DataModels\Orchid.DataModels.csproj" />
    <ProjectReference Include="..\Orchid.EmailService\Orchid.EmailService.csproj" />
    <ProjectReference Include="..\Orchid.TokenValidator\Orchid.TokenValidator.csproj" />
    <ProjectReference Include="..\Orchid.UtilityHelper\Orchid.UtilityHelper.csproj" />
  </ItemGroup>

</Project>
